INSERT INTO breeder(name, username, password, email, dog_url) VALUES('Samson Smith0', 'username', 'password', 'funnyemail@gmail.com', '');
INSERT INTO dog(name, breed, age, mother, father, b_id) VALUES('Oakley', 'Labrador Retriever', '2', 'momma dog', 'papa dog', 1);
INSERT INTO dog(name, breed, age, mother, father, b_id) VALUES('Mojo', 'Labrador Retriever', '3', 'momma dog', 'papa dog', 1);
INSERT INTO dog(name, breed, age, mother, father, b_id) VALUES('Halo', 'Labrador Retriever', '5', 'momma dog', 'papa dog', 1);
INSERT INTO dog(name, breed, age, mother, father, b_id) VALUES('Lady', 'Labrador Retriever', '1', 'momma dog', 'papa dog', 1);
INSERT INTO dog(name, breed, age, mother, father, b_id) VALUES('Dock', 'Labrador Retriever', '3', 'momma dog', 'papa dog', 1);
INSERT INTO dog(name, breed, age, mother, father, b_id) VALUES('Spot', 'Labrador Retriever', '2', 'momma dog', 'papa dog', 1);
INSERT INTO dog(name, breed, age, mother, father, b_id) VALUES('Chap', 'Labrador Retriever', '4', 'momma dog', 'papa dog', 1);
INSERT INTO dog(name, breed, age, mother, father, b_id) VALUES('Daisy', 'Labrador Retriever', '5', 'momma dog', 'papa dog', 1);
INSERT INTO dog(name, breed, age, mother, father, b_id) VALUES('Charlie', 'Labrador Retriever', '6', 'momma dog', 'papa dog', 1);
INSERT INTO dog(name, breed, age, mother, father, b_id) VALUES('Simba', 'Labrador Retriever', '7', 'momma dog', 'papa dog', 1);
INSERT INTO dog(name, breed, age, mother, father, b_id) VALUES('Jake', 'Labrador Retriever', '1', 'momma dog', 'papa dog', 1);
INSERT INTO dog(name, breed, age, mother, father, b_id) VALUES('James', 'Labrador Retriever', '2', 'momma dog', 'papa dog', 1);

INSERT INTO breeder(name, username, password, email, dog_url) VALUES('Noah White', 'newUser', 'password', 'test@email.com', '');
INSERT INTO breeder(name, username, password, email, dog_url) VALUES('James Smith', 'otherUser', 'password', 'something@email.com', '');
INSERT INTO breeder(name, username, password, email, dog_url) VALUES('Josh Wayne', 'someUser', 'password', 'testing@email.com', '');
INSERT INTO breeder(name, username, password, email, dog_url) VALUES('Charles Johnson', 'john10', 'password', 'tes1@email.com', '');
INSERT INTO breeder(name, username, password, email, dog_url) VALUES('Thomas Wayne', 'tom tom', 'password', 'thomas@email.com', '');
INSERT INTO breeder(name, username, password, email, dog_url) VALUES('Lewis Sharp', 'lew lew', 'password', 'lewlew@email.com', '');
INSERT INTO breeder(name, username, password, email, dog_url) VALUES('John Ballard', 'allard1', 'password', 'ballard@email.com', '');
INSERT INTO breeder(name, username, password, email, dog_url) VALUES('Ricky Sharp', 'rickrick', 'password', 'rickrick@email.com','');